demo_django/urls.py
from django.contrib import admin
from django.urls import path
from app01 import views
from app01.views import main, algorithm, simulation, target, user
urlpatterns = [
    # path('admin/', admin.site.urls),
    path('main/', main.main),
    path('main/goods_list', main.goods_list),
    path('main/policy_simulation', simulation.policy_simulation),
    path('main/simu_history', simulation.simu_history),
    path('register/', main.register),
    path('super/login', main.super_login),
    # path('super/use', views.super_use),


    # path('test/tpl', views.tpl),
    # path('test/something', views.something),
    # path('test/login', views.login),


    # path('info/list', views.info_list),
    # path('info/add', views.info_add),
    # path('info/delete/', views.info_delete)


    path('depart/list/', algorithm.algorithm_list),
    path('depart/add/', algorithm.algorithm_add),
    path('depart/delete/', algorithm.algorithm_delete),
    path('depart/<int:nid>/edit/', algorithm.algorithm_edit),

    path('user/list/', user.user_list),
    # path('user/add/', views.user_add),
    path('user/model/form/add/', user.user_model_form_add),
    path('user/<int:nid>/edit/', user.user_edit),
    path('user/<int:nid>/delete/', user.user_delete),

    path('target/list/', target.target_list),
    path('target/add/', target.target_add),
    path('target/delete/', target.target_delete),
    path('target/<int:nid>/edit/', target.target_edit),

]

app01/models.py
from django.contrib.auth.models import UserManager
from django.db import models
from django.db import models


class Department(models.Model):
    """ 部门表 """
    title = models.CharField(max_length=32, verbose_name='标题')

    def __str__(self):
        return self.title


class UserInfo(models.Model):
    """员工表"""
    name = models.CharField(max_length=16, verbose_name='姓名')
    password = models.CharField(max_length=64, verbose_name='密码')
    age = models.IntegerField(verbose_name='年龄')
    account = models.DecimalField(verbose_name='账户余额', max_digits=10, decimal_places=2, default=0)
    create_time = models.DateField(verbose_name='入职时间', null=True, blank=True)
    depart = models.ForeignKey(to='Department', to_field="id", on_delete=models.CASCADE, verbose_name="部门", null=True,
                               blank=True)
    gender_choices = (
        (1, "男"),
        (0, "女"),
    )
    gender = models.SmallIntegerField(verbose_name='性别', choices=gender_choices, null=True, blank=True)


class Target(models.Model):
    """ 指标表 """
    target = models.CharField(max_length=32, verbose_name='指标')

    def __str__(self):
        return self.target


class Algorithm(models.Model):
    """ 指标表 """
    algorithm = models.CharField(max_length=32, verbose_name='算法')

    def __str__(self):
        return self.algorithm


class Simulation(models.Model):
    """政策模拟表"""
    target = models.ForeignKey(to='Target', to_field='id', on_delete=models.CASCADE)
    algorithm = models.ForeignKey(to='Algorithm', to_field='id', on_delete=models.CASCADE)
    data = models.IntegerField(verbose_name='数据')
    time = models.DateField(verbose_name='时间参数', null=True, blank=True)
    outcome = models.IntegerField(verbose_name='模拟结果', null=True, blank=True)


class Admin(models.Model):
    """管理员"""
    username = models.CharField(verbose_name="用户名", max_length=32)
    password = models.CharField(verbose_name="密码", max_length=64)

app01/views/algorithm.py
from django.shortcuts import render, redirect
from app01 import models


def algorithm_list(request):
    """算法列表"""
    queryset = models.Algorithm.objects.all()
    return render(request, "algorithm_list.html", {'queryset': queryset})


def algorithm_add(request):
    """添加算法"""
    if request.method == "GET":
        return render(request, "algorithm_add.html")
    """获取用户通过post输入的数据"""
    algorithm = request.POST.get('algorithm')
    """保存到数据库"""
    models.Algorithm.objects.create(algorithm=algorithm)
    """重定向"""
    return redirect("/depart/list/")


def algorithm_delete(request):
    """删除算法"""
    nid = request.GET.get('nid')
    models.Algorithm.objects.filter(id=nid).delete()
    return redirect("/depart/list/")


def algorithm_edit(request, nid):
    """修改算法"""
    if request.method == "GET":
        row_obj = models.Algorithm.objects.filter(id=nid).first()
        return render(request, 'algorithm_edit.html', {"row_obj": row_obj})
    algorithm = request.POST.get("algorithm")
    models.Algorithm.objects.filter(id=nid).update(algorithm=algorithm)
    return redirect("/depart/list/")

app01/views/simulation.py
from django.shortcuts import render, redirect
from app01 import models


def policy_simulation(request):
    """原始版"""
    target_queryset = models.Target.objects.all()
    algorithm_queryset = models.Algorithm.objects.all()

    if request.method == "GET":
        return render(request, "policy_simulation.html",
                      {'target_queryset': target_queryset, 'algorithm_queryset': algorithm_queryset})
    target = request.POST.get("target")
    algorithm = request.POST.get("algorithm")
    time = request.POST.get("time")
    data = request.POST.get("data")
    outcome = int(data) * 2
    models.Simulation.objects.create(target_id=target, algorithm_id=algorithm, data=data, outcome=outcome, time=time)

    # return redirect("/main/policy_simulation")
    return redirect("/main/simu_history")


def simu_history(request):
    """展示模拟历史"""
    queryset = models.Simulation.objects.all()
    return render(request, 'simu_history.html', {'queryset': queryset})

app01/views/target.py
from django.shortcuts import render, redirect
from app01 import models
from app01.utills.form import UserModelForm

"""对指标的操作"""


def target_list(request):
    """指标列表"""
    queryset = models.Target.objects.all()
    return render(request, "target_list.html", {'queryset': queryset})


def target_add(request):
    """添加指标"""
    if request.method == "GET":
        return render(request, "target_add.html")
    """获取用户通过post输入的数据"""
    target = request.POST.get('target')
    """保存到数据库"""
    models.Target.objects.create(target=target)
    """重定向"""
    return redirect("/target/list/")


def target_delete(request):
    """删除指标"""
    nid = request.GET.get('nid')
    models.Target.objects.filter(id=nid).delete()
    return redirect("/target/list/")


def target_edit(request, nid):
    """修改指标"""
    if request.method == "GET":
        row_obj = models.Target.objects.filter(id=nid).first()
        return render(request, 'target_edit.html', {"row_obj": row_obj})
    target = request.POST.get("target")
    models.Target.objects.filter(id=nid).update(target=target)
    return redirect("/target/list/")

app01/views/user.py
from django.shortcuts import render, redirect
from app01 import models
from app01.utills.form import UserModelForm

""""对用户的操作"""


def user_list(request):
    """用户列表"""
    queryset = models.UserInfo.objects.all()
    return render(request, "user_list.html", {'queryset': queryset})


def user_model_form_add(request):
    if request.method == "GET":
        form = UserModelForm()
        return render(request, "user_model_form_add.html", {"form": form})
    form = UserModelForm(data=request.POST)
    if form.is_valid():  # 校验数据是否合法
        print(form.cleaned_data)
        form.save()  # 将数据保存到数据库
        return redirect('/user/list/')
    else:
        return render(request, "user_model_form_add.html", {"form": form})


def user_edit(request, nid):
    """编辑用户"""

    # 根据nid获取要编辑的那一行的数据
    row_obj = models.UserInfo.objects.filter(id=nid).first()
    if request.method == "GET":
        # 在编辑页面开始先显示原始数据
        form = UserModelForm(instance=row_obj)
        return render(request, "user_edit.html", {'form': form})
    form = UserModelForm(data=request.POST, instance=row_obj)  # instance指向你要更新的对象
    if form.is_valid():
        # 如果想保存用户输入以外的一些值,可以用 'form.instance.字段名 = 值'
        form.save()
        return redirect('/user/list')
    return render(request, 'user_edit.html', {'form': form})


def user_delete(request, nid):
    """删除用户"""
    models.UserInfo.objects.filter(id=nid).delete()
    return redirect('/user/list/')

app01/templates/algorithm_add.html
{% extends 'layout.html' %}             {#引入模板#}

{% block content %}
    <div class="container">
                <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">新增算法</h3>
          </div>
          <div class="panel-body">
              <form method="post" >
                  {% csrf_token %}
                  <div class="form-group">
                    <label >算法名</label>
                    <input type="text" class="form-control" placeholder="算法名" name="algorithm">
                  </div>
                  <button type="submit" class="btn btn-success">保 存</button>
              </form>
          </div>
        </div>
    </div>
{% endblock %}

app01/templates/algorithm_list.html
{#管理员界面的算法列表#}
{% extends "layout.html" %}


{% block content %}
    <div class="container">
        <div style="margin-bottom:10px;">
            <a class="btn btn-success" href="/depart/add/" >
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                新建算法
            </a>
        </div>


<div class="panel panel-default">
      <!-- Default panel contents -->
      <div class="panel-heading">
          <span class="glyphicon glyphicon-th" aria-hidden="true"></span>
          算法列表
      </div>

      <!-- Table -->
      <table class="table">
        <thead>
          <tr>
            <th>ID</th>
            <th>名称</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
        {% for obj in queryset %}
          <tr>
            <th scope="row">{{ obj.id }}</th>
            <td>{{ obj.algorithm }}</td>
            <td>
                <a class="btn btn-primary btn-xs" href="/depart/{{ obj.id }}/edit/"> 编辑</a>
                <a class="btn btn-danger btn-xs" href="/depart/delete/?nid={{ obj.id }}"> 删除</a>
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
    </div>
{% endblock %}

app01/templates/goods_list.html
{#用户界面的算法列表#}

{% extends "main_layout.html" %}

{% block content %}
    <div class="container-fluid clearfix">
    <div class="col-sm-9">
        <div class="media">

            <div class="media-body">
                <h4 class="media-heading">粒子群算法</h4>
                粒子群算法，也称粒子群优化算法或鸟群觅食算法（Particle Swarm Optimization），缩写为 PSO， 是由J. Kennedy和R. C.
                Eberhart等开发的一种新的进化算法(Evolutionary Algorithm - EA)。PSO 算法属于进化算法的一种，
                和模拟退火算法相似，它也是从随机解出发，通过迭代寻找最优解，它也是通过适应度来评价解的品质，但它比遗传算法规则更为简单， 它没有遗传算法的“交叉”(Crossover) 和“变异”(Mutation)
                操作，它通过追随当前搜索到的最优值来寻找全局最优。 这种算法以其实现容易、精度高、收敛快等优点引起了学术界的重视，并且在解决实际问题中展示了其优越性。粒子群算法是一种并行算法。
            <a href="#">更多</a>
            </div>

        </div>
        <div class="media">

            <div class="media-body">
                <h4 class="media-heading">蚁群算法</h4>
                蚁群算法是一种智能优化算法，在TSP商旅问题上得到广泛使用。蚁群算法于1992年由Marco
                Dorigo首次提出，该算法来源于蚂蚁觅食行为。由于蚂蚁没有视力，所以在寻找食物源时，会在其经过的路径上释放一种信息素，并能够感知其它蚂蚁释放的信息素。信息素浓度的大小表征路径的远近，信息素浓度越高，表示对应的路径距离越短。通常，蚂蚁会以较大的概率优先选择信息素浓度高的路径，并且释放一定的信息素，使该条路径上的信息素浓度增高，进而使蚂蚁能够找到一条由巢穴到食物源最近的路径。但是，随着时间的推移，路径上的信息素浓度会逐渐衰减。
                粒子群算法，也称粒子群优化算法或鸟群觅食算法（Particle Swarm Optimization），缩写为 PSO， 是由J. Kennedy和R. C.
                Eberhart等开发的一种新的进化算法(Evolutionary Algorithm - EA)。PSO 算法属于进化算法的一种，
                和模拟退火算法相似，它也是从随机解出发，通过迭代寻找最优解，它也是通过适应度来评价解的品质，但它比遗传算法规则更为简单， 它没有遗传算法的“交叉”(Crossover) 和“变异”(Mutation)
                操作，它通过追随当前搜索到的最优值来寻找全局最优。 这种算法以其实现容易、精度高、收敛快等优点引起了学术界的重视，并且在解决实际问题中展示了其优越性。粒子群算法是一种并行算法。
            <a href="#">更多</a>
            </div>
        </div>


        <ul class="pagination">
            <li class="disabled"><a href="#" aria-label="Previous"><span aria-hidden="true">«</span></a></li>
            <li class="active"><a href="#">1 <span class="sr-only">(current)</span></a></li>
            <li><a href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">4</a></li>
            <li><a href="#">5</a></li>
            <li><a href="#" aria-label="Next"><span aria-hidden="true">»</span></a></li>
        </ul>
    </div>
    <div class="col-sm-3">
        <div class="panel panel-primary">
            <div class="panel-heading">最火政策推荐</div>
            <div class="panel-body">
                粒子群算法
            </div>
        </div>
        <div class="panel panel-danger">
            <div class="panel-heading">最新政策推荐</div>
            <div class="panel-body">
                蚁群算法
            </div>
        </div>
    </div>
</div>
{% endblock %}

app01/templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.css' %}">
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <style>
        body {
            font-family: 'Montserrat', sans-serif;
        }
        .thumbnail {
            border:none;
            box-shadow: 0 3px 3px #c1c1c1;
            height: 407px;
        }
    </style>
</head>
<body>
<nav class="navbar navbar-default" style="box-shadow: 0 3px 3px white;">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">经济数据预测平台</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li ><a href="/main">首页</a></li>
                <!--                <li class="active"><a href="#">政策列表<span class="sr-only">(current)</span></a></li>-->
                <li><a href="/main/goods_list">政策列表</a></li>
                <li><a href="/main/policy_simulation">政策模拟</a></li>
                <li><a href="#">开通会员</a></li>
                <li><a href="#">联系我们</a></li>
            </ul>
            <form class="navbar-form navbar-left">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search">
                </div>
{#                <button type="submit" class="btn btn-default">#}
{#                    <i class="fa fa-search" aria-hidden="true"></i>#}
{#                </button>#}
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">设置</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">我的 <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">账号管理</a></li>
                        <li><a href="#">我的会员</a></li>
                        <li><a href="#">收藏夹</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">注销账号</a></li>
                        <li><a href="#">退出登录</a></li>
                    </ul>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

<div class="jumbotron" style="background-color: hsl(0deg 0% 100% / 0%);">
    <div class="container">
        <h1>欢迎!</h1>
        <p>我们的平台基于神经网络算法，可以帮助您进行政策模拟，确定政策作出某一变化后对社会的影响，是您学术研究道路上的一大助力。</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">了解更多</a></p>
    </div>
</div>

<div class="row">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail" style="margin-left:200px;">
      <img src="{% static 'img/ZhuYe_1.png' %}" alt="..." style="height:150px;">
      <div class="caption">
        <h3>海量算法</h3>
        <p>我们的平台基于神经网络算法，可以帮助您进行政策模拟，确定政策作出某一变化后对社会的影响，是您学术研究道路上的一大助力。</p>
        <p><a href="#" class="btn btn-primary" role="button">详细信息</a> <a href="#" class="btn btn-default" role="button">关于</a></p>
      </div>
    </div>
  </div>

      <div class="col-sm-6 col-md-4">
    <div class="thumbnail" >
      <img src="{% static 'img/ZhuYe_2.png' %}" alt="..." style="height:150px;">
      <div class="caption">
        <h3>精准预测</h3>
        <p>我们的平台基于神经网络算法，可以帮助您进行政策模拟，确定政策作出某一变化后对社会的影响，是您学术研究道路上的一大助力。</p>
       <p><a href="#" class="btn btn-primary" role="button">详细信息</a> <a href="#" class="btn btn-default" role="button">关于</a></p>
      </div>
    </div>
  </div>

      <div class="col-sm-6 col-md-4">
    <div class="thumbnail" style="margin-right:200px;">
      <img src="{% static 'img/ZhuYe_3.png' %}" alt="..." style="height:150px;">
      <div class="caption">
        <h3>权威发布</h3>
        <p>我们的平台基于神经网络算法，可以帮助您进行政策模拟，确定政策作出某一变化后对社会的影响，是您学术研究道路上的一大助力。</p>
        <p><a href="#" class="btn btn-primary" role="button">详细信息</a> <a href="#" class="btn btn-default" role="button">关于</a></p>

      </div>
    </div>
  </div>
</div>

<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-3.4.1/js/bootstrap.min.js' %}"></script>

</body>
</html>

app01/templates/main_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>政策模拟</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.css' %}">
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    {% block css %}{% endblock %}
</head>

<body>
<nav class="navbar navbar-default" style="box-shadow: 0 3px 3px #c1c1c1;">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">经济数据预测平台</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li ><a href="/main">首页</a></li>
                <li><a href="/main/goods_list">政策列表</a></li>
                <li><a href="/main/policy_simulation">政策模拟</a>
                </li>
                <!--                <li><a href="#">政策列表</a></li>-->
                <li><a href="/main/simu_history">模拟历史</a></li>
                <li><a href="#">开通会员</a></li>
                <li><a href="#">联系我们</a></li>
{#                <li class="dropdown">#}
{#                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"#}
{#                       aria-expanded="false">类型 <span class="caret"></span></a>#}
{#                    <ul class="dropdown-menu">#}
{#                        <li><a href="#">工业</a></li>#}
{#                        <li><a href="#">农业</a></li>#}
{#                        <li><a href="#">畜牧业</a></li>#}
{#                        <li role="separator" class="divider"></li>#}
{#                        <li><a href="#">全部</a></li>#}
{#                        <!--                        <li role="separator" class="divider"></li>-->#}
{#                        <!--                        <li><a href="#">One more separated link</a></li>-->#}
{#                    </ul>#}
{#                </li>#}
            </ul>
            <form class="navbar-form navbar-left">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search">
                </div>
                {#                <button type="submit" class="btn btn-default">#}
                {#                    <i class="fa fa-search" aria-hidden="true"></i>#}
                {#                </button>#}
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">设置</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">我的 <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">账号管理</a></li>
                        <li><a href="#">我的会员</a></li>
                        <li><a href="#">收藏夹</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">注销账号</a></li>
                        <li><a href="#">退出登录</a></li>
                    </ul>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

<div>
        {% block content %}{% endblock %}
</div>

<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-3.4.1/js/bootstrap.min.js' %}"></script>
{% block js %}{% endblock %}
</body>
</html>

app01/templates/pretty_add.html
{% extends "layout.html" %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">新增靓号</h3>
            </div>
            <div class="panel-body">
                <form method="post" novalidate>
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">
                            <label>{{ field.label }}</label>
                            {{ field }}
                            <span style="color: red">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-success">保 存</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

app01/templates/pretty_edit.html
{% extends "layout.html" %}
{% block content %}
        <div class="container">
                <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">编辑靓号</h3>
          </div>
          <div class="panel-body">
              <form method="post" novalidate>
                  {% csrf_token %}
                    {% for field in form%}
                        <div class="form-group">
                            <label>{{ field.label }}</label>
                            {{ field }}
                            <span style="color: red">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}
                  <button type="submit" class="btn btn-success">保 存</button>
              </form>
          </div>
        </div>
    </div>
{% endblock %}

app01/templates/super_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.css' %}">
    <style>
        .account {
            border: 5px solid #2aabd2;
            width: 500px;
            height: 350px;
            margin: 100px auto 0;
            padding: 20px 40px;
            border-radius: 20px;
            /*box-shadow:阴影*/
            box-shadow: 10px 10px 5px #c1c1c1;
        }

        .account h1 {
            text-align: center;
        }
    </style>
</head>
<body>
<div class="account">
    <h2>管理员登录</h2>
    <form action="/superUse">
        <div class="form-group">
            <label for="exampleInputEmail1">用户名</label>
            <input type="text" class="form-control" id="exampleInputEmail1" placeholder="请输入用户名">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">密码</label>
            <input type="password" class="form-control" id="exampleInputPassword1" placeholder="请输入密码">
        </div>
        <button type="submit" class="btn btn-info"> 登 录</button>
    </form>
</div>
</body>
</html>

app01/templates/user_list.html
{% extends "layout.html" %}

{% block content %}
    <div class="container">

        <div style="margin-bottom:10px;">
            <a class="btn btn-success" href="/user/model/form/add/" >
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                新建用户
            </a>
        </div>


        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th" aria-hidden="true"></span>
                用户列表
            </div>

            <!-- Table -->
            <table class="table">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>姓名</th>
                    <th>密码</th>
                    <th>年龄</th>
                    <th>余额</th>
                    <th>入职时间</th>
                    <th>性别</th>
                    <th>算法</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in queryset %}
                    <tr>
                        <th scope="row">{{ obj.id }}</th>
                        <td>{{ obj.name }}</td>
                        <td>{{ obj.password }}</td>
                        <td>{{ obj.age }}</td>
                        <td>{{ obj.account }}</td>
                        <td>{{ obj.create_time|date:"Y-m-d" }}</td>
                        <td>{{ obj.get_gender_display }}</td>
                        <td>{{ obj.depart.title }}</td>
                        <td>
                            <a class="btn btn-primary btn-xs" href="/user/{{ obj.id }}/edit/"> 编辑</a>
                            <a class="btn btn-danger btn-xs" href="/user/{{ obj.id }}/delete/"> 删除</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock %}

app01/templates/user_model_form_add.html
{% extends "layout.html" %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css' %}" >
{% endblock %}
{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">新增用户</h3>
            </div>
            <div class="panel-body">
                <form method="post" novalidate>
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">
                            <label>{{ field.label }}</label>
                            {{ field }}
                            <span style="color: red">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-success">保 存</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}


{% block js %}
{#    <link rel="stylesheet" href="{% static 'plugins/bootstrap-datepicker/js/bootstrap-datepicker.js' %}" >#}
{#    <link rel="stylesheet" href="{% static 'plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js' %}" >#}
    <script src="{% static 'plugins/bootstrap-datepicker/js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js' %}"></script>
    <script>
        $(function () {
            $('#id_create_time').datepicker({
                format: 'yyyy-mm-dd',
                startDate: '0',
                language: "zh-CN",
                autoclose: true
            });

        })
    </script>
{% endblock %}